[INFO   ] Logger: Record log in /storage/emulated/0/kivy-json/.kivy/logs/kivy_22-04-06_4.txt
[INFO   ] Kivy: v2.0.0
[INFO   ] Kivy: Installed at "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.9/site-packages/kivy/__init__.py"
[INFO   ] Python: v3.9.7 (default, Oct  6 2021, 01:34:26) 
[GCC 11.1.0]
[INFO   ] Python: Interpreter at "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/bin/python3"
[WARNING] stderr: Traceback (most recent call last):
[WARNING] stderr:   File "/storage/emulated/0/kivy-json/main.py", line 11, in <module>
[WARNING] stderr:     print('tito is', store.get('tito'))
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.9/site-packages/kivy/storage/__init__.py", line 159, in get
[WARNING] stderr:     return self.store_get(key)
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.9/site-packages/kivy/storage/jsonstore.py", line 63, in store_get
[WARNING] stderr:     return self._data[key]
[WARNING] stderr: KeyError: 'tito'
